version: '2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: 'juan'
      POSTGRES_PASSWORD: '1234'
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/proyecto2
    ports:
      - "3000:3000"
    depends_on:
      - db